### ISSUE TITLE
game over menu after collision with enemy

### ISSUE THREAD

**Issue by jprolejko** [SpiritStudio/Spirit-Runner#3]
game over menu appears only after the collision with fire (it should appear always when dead)

**Comment by danielm1405** [comment]
Further details about repository usage are needed to fix the issue.

**Comment by jprolejko** [comment]
I think we can bring our computers to the meeting and i'll explain you everything.

**Comment by jprolejko** [comment]
also, reset after death of the player sometimes doesn't work well (he dies again)
